#!/bin/bash

# Helper script to display GitHub secrets configuration
# Run this ON YOUR EC2 INSTANCE after setup

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "GitHub Secrets Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Add these secrets to your GitHub repository:"
echo "Go to: Settings → Secrets and variables → Actions → New repository secret"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Secret 1: AWS_EC2_HOST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Name: AWS_EC2_HOST"
echo "Value:"
echo ""
curl -s http://169.254.169.254/latest/meta-data/public-ipv4
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Secret 2: AWS_EC2_USER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Name: AWS_EC2_USER"
echo "Value:"
echo ""
echo "ubuntu"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Secret 3: AWS_SSH_KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Name: AWS_SSH_KEY"
echo "Value: (paste the ENTIRE contents of your .pem key file)"
echo ""
echo "To get your .pem file contents:"
echo ""
echo "Windows (PowerShell):"
echo "  Get-Content flowgrid-key.pem | clip"
echo ""
echo "Mac:"
echo "  cat flowgrid-key.pem | pbcopy"
echo ""
echo "Linux:"
echo "  cat flowgrid-key.pem | xclip -selection clipboard"
echo ""
echo "Or open the .pem file in a text editor and copy everything"
echo "including the BEGIN and END lines."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After adding all secrets, push to main branch to trigger deployment!"
echo ""
